language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-22
    - extra-android-m2repository

script:
  - ./gradlew build connectedCheck
